- name: add nginx config header for fileserver
  blockinfile:
    path: /etc/nginx/sites-available/fileserver.rstms.net
    marker: '# ansible_managed header_block {mark}'
    insertbefore: BOF
    block: |
     upstream fileserver-proxy {
       server 127.0.0.1:8000;
     }

- name: comment out try_files line, change to proxy_config
  lineinfile:
    path: /etc/nginx/sites-available/fileserver.rstms.net
    regexp: '^(\s*)(try_files.*)$'
    line: '# proxy_config'

- name: add nginx config proxy header
  blockinfile:
    path: /etc/nginx/sites-available/fileserver.rstms.net
    marker: '# ansible_managed location_block {mark}'
    insertafter: '# proxy_config.*'
    block: |
       proxy_pass                          http://fileserver-proxy;
       proxy_set_header  Host              $http_host;   # required for docker client's sake
       proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
       proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
       proxy_set_header  X-Forwarded-Proto $scheme;

- name: check nginx config files for errors
  command: nginx -t
  register: status_config

- debug: 'msg={{ status_config }}'

- name: restart nginx
  command: systemctl restart nginx
